### ISSUE TITLE
FileTreeRepository#register does not report failures on MacOS

### ISSUE THREAD

**Issue by pvid** [swoval/swoval#145]
Originally taken from https://github.com/scalameta/metals/issues/2961#issuecomment-885193246

> After some fun with the debugger, I found out that the filesystem is returning an invalid stream handle and the ApplePathPatcher#register is returning a false, [see](https://github.com/swoval/swoval/blob/develop/files/jvm/src/main/java/com/swoval/files/ApplePathWatcher.java#L111). However, the result is disregarded one level up in FileCacheDirectoryTree [here](https://github.com/swoval/swoval/blob/9d62a35fee13872dba7fc1e98e20850880fe2198/files/jvm/src/main/java/com/swoval/files/FileCacheDirectoryTree.java#L417). Even the docstring for ApplePathWatcher#register does not mention that it return a false in case of registration failure.

The issue is that the caller is not informed in case of failure while registering a FSEvent stream which happens after exhausting a global OS limit. 

What would think about returning a `Left(IOException)` in case of an invalid handle? That would align with the docs.

**Comment by pvid** [comment]
BTW, I'd love to help out with sorting this out, but I currently can't make any promises due to other commitments. However, I will try to follow up with a PR when I find the time

**Comment by eatkins** [comment]
Thanks. I agree that returning Left(IOException) would be the correct approach. We should also be doing that at line 119: https://github.com/swoval/swoval/blob/9d62a35fee13872dba7fc1e98e20850880fe2198/files/jvm/src/main/java/com/swoval/files/ApplePathWatcher.java#L117-L120

I have other things on my plate as well so I can't promise that I will work on this soon, but I think we're in agreement on what the next steps should be. If I do make a PR, I'll be sure to cc you. Otherwise I'll wait for your PR :)

**Comment by eatkins** [comment]
I released v2.1.7 which incorporates #149.
