### ISSUE TITLE
Registering a watch on a missing file does not work

### ISSUE THREAD

**Issue by pvid** [swoval/swoval#146]
I encountered the issue while working on the `metals` FileWatcher. It is probably related to https://github.com/swoval/swoval/pull/135

Here is a failing test case adapted from https://github.com/swoval/swoval/blob/9d62a35fee13872dba7fc1e98e20850880fe2198/files/shared/src/test/scala/com/swoval/files/BasicFileCacheTest.scala#L342

```scala
'missingFile - withTempDirectory { dir =>
  implicit val logger: TestLogger = new CachingLogger
  withTempDirectory(dir) { subdir =>
    val latch = new CountDownLatch(1)
    val subdir2 = subdir.resolve("sub")
    val subdir3 = subdir2.resolve("sub")
    val subdir4 = subdir3.resolve("sub")
    val file = subdir4.resolve("file")
    usingAsync(simpleCache((e: Entry[Path]) => if (e.path == file) latch.countDown())) { c =>
      Files.createDirectories(subdir4)
      c.reg(file, true)
      c.ls(subdir4) === Set.empty[Path]
      file.createFile()
      latch.waitFor(DEFAULT_TIMEOUT) {
        c.ls(subdir4) === Set(file)
      }
    }
  }
}
```

**Comment by pvid** [comment]
However, there is a chance that I am misunderstanding how it should be working

**Comment by eatkins** [comment]
Thanks for the report! Your understanding seems correct to me. I would expect the adapted test to pass so if it doesn't, that definitely is a bug.

**Comment by eatkins** [comment]
This is a bit subtle and I misinterpreted the test case. The library actually was working as intended although it isn't necessarily obvious at a glance (which is why I missed it myself). The list method of file cache only returns records for directories and paths that were specifically registered with the cache. In the test case you provided, it was actually expected that listing subdir-4 would be empty because that directory was not registered with the cache. Changing the test case to list the file instead fixes the test.

**Comment by pvid** [comment]
Thank you for looking into this and the explanation! It is a big help 👍
